### ISSUE TITLE
why the tf_hub elmo embedding changes if the batch input has an extra sentence?

### ISSUE THREAD

**Issue by jzhangsales** [tensorflow/hub#369]
for example, the input sentences=["word"], the module by default would give a pooled vector for "word".
if one changes sentences=["word", "vector change !"], the output is a list of 2 vectors. the first one is the embed vector for "word", but this one is not exactly the same from the above one.

any clue how this happens? thanks!

**Comment by rmothukuru** [comment]
@jzhangsales ,
Tried reproducing your issue with the below code. I got almost the same output using your inputs. Can you please provide more details about your issue. Thanks!

```
import tensorflow_hub as hub

elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)
embeddings = elmo(["word"], signature="default",  as_dict=True)
embeddings

Output:
{'lstm_outputs1': <tf.Tensor 'module_1_apply_default/concat:0' shape=(1, ?, 1024) dtype=float32>,
 'lstm_outputs2': <tf.Tensor 'module_1_apply_default/concat_1:0' shape=(1, ?, 1024) dtype=float32>,
 'word_emb': <tf.Tensor 'module_1_apply_default/bilm/Reshape_1:0' shape=(1, 1, 512) dtype=float32>,
 'sequence_len': <tf.Tensor 'module_1_apply_default/Sum:0' shape=(1,) dtype=int32>,
 'elmo': <tf.Tensor 'module_1_apply_default/aggregation/mul_3:0' shape=(1, ?, 1024) dtype=float32>,
 'default': <tf.Tensor 'module_1_apply_default/truediv:0' shape=(1, 1024) dtype=float32>}

elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)
embeddings = elmo(["word", "vector change !"], signature="default",  as_dict=True)
embeddings

Output:
{'sequence_len': <tf.Tensor 'module_2_apply_default/Sum:0' shape=(2,) dtype=int32>,
 'elmo': <tf.Tensor 'module_2_apply_default/aggregation/mul_3:0' shape=(2, 3, 1024) dtype=float32>,
 'default': <tf.Tensor 'module_2_apply_default/truediv:0' shape=(2, 1024) dtype=float32>,
 'lstm_outputs1': <tf.Tensor 'module_2_apply_default/concat:0' shape=(2, ?, 1024) dtype=float32>,
 'lstm_outputs2': <tf.Tensor 'module_2_apply_default/concat_1:0' shape=(2, ?, 1024) dtype=float32>,
 'word_emb': <tf.Tensor 'module_2_apply_default/bilm/Reshape_1:0' shape=(2, 3, 512) dtype=float32>}
```

**Comment by leifvan** [comment]
Hi @rmothukuru, I guess the issue @jzhangsales refers to has to do with the actual values of the vector representation you get for 'word', not with the shapes. We actually ran into a similar issue a couple weeks ago at our institute and hadn't looked into it until now.

I created a gist reproducing the problem:
https://gist.github.com/leifvan/1f1a8c957dcf9f3b76bfd3bb687f88b7

In short, the difference of outputs from above seems to stem from a padding issue. For the 'default' output, elmo calculates a fixed-mean pooling of the word-level outputs of the 'elmo' output. But it considers all word vectors, including the ones from the padded part of the input. Maybe it is assumed that there should only be zeros, but that's not true (see gist).

A quick fix would be to calculate the pooling step manually - only considering the valid parts of the output:

```python
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)
embeddings = elmo(["word", "vector change !"], signature="default",  as_dict=True)
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  # get the output for "word" while also passing "vector change !"
  raw_token_output = sess.run(embeddings['elmo'])[0]
# the sentence "word" consist of only one token:
actual_num_tokens = 1
# calculate the vector by only considering the valid part of the output
valid_vector = np.sum(raw_token_output[:actual_num_tokens], axis=0) / actual_num_tokens
```

The gist shows this in more detail and also confirms that the valid part of the output stays the same when the padding length changes.

**Comment by leifvan** [comment]
Judging from the changelog, it seems this issue was fixed in the newest version (3) of Elmo.

**Comment by miguelangelsg** [comment]
Hi, 

I am using ELMo3 and I think the problem persists:

`
import tensorflow as tf
import tensorflow_hub as hub

elmo = hub.Module("https://tfhub.dev/google/elmo/3", trainable=False)

print("""Sample #1: three sentences""")
sample_1 = [
    "so close",
    "no matter how far",
    "couldn't be much more from the heart",
]
sample_1 = [s.split() for s in sample_1]
sample_1_lens = [len(s) for s in sample_1]
sample_1_max_l = max(sample_1_lens)
print('max len of sentence %s'%sample_1_max_l)

#Padding
sample_1_pad = []
for s in sample_1:
    sample_1_pad.append(s+['']*(sample_1_max_l - len(s)))
            
            
embeddings_1 = elmo(inputs={
                            'tokens':sample_1_pad,
                            'sequence_len':sample_1_lens
                            }, 
                    signature="tokens", as_dict=True)["elmo"]
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sample_1_elmo = sess.run(embeddings_1)

            
print("""\nSample #2: Two sentences""")
sample_2 = [
    "so close",
#     "no matter how far",
    "couldn't be much more from the heart",
]
sample_2 = [s.split() for s in sample_2]
sample_2_lens = [len(s) for s in sample_2]
sample_2_max_l = max(sample_2_lens)
print('max len of sentence %s'%sample_2_max_l)

#Padding
sample_2_pad = []
for s in sample_2:
    sample_2_pad.append(s+['']*(sample_2_max_l - len(s)))
            
            
embeddings_2 = elmo(inputs={
                            'tokens':sample_2_pad,
                            'sequence_len':sample_2_lens
                            }, 
                    signature="tokens", as_dict=True)["elmo"]
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sample_2_elmo = sess.run(embeddings_2)

print('\nLast sentence vector comparison')
print('1e-15 precision: %s different'%((sample_1_elmo[-1,:,:] - sample_2_elmo[-1,:,:] > 1e-15).sum()))
print('1e-8 precision: %s different'%((sample_1_elmo[-1,:,:] - sample_2_elmo[-1,:,:] > 1e-8).sum()))
print('1e-6 precision: %s different'%((sample_1_elmo[-1,:,:] - sample_2_elmo[-1,:,:] > 1e-6).sum()))
`

**Comment by rmothukuru** [comment]
@jzhangsales, 
Closing the issue as it has been fixed in [Elmo-3](https://tfhub.dev/google/elmo/3). Thanks!
