### ISSUE TITLE
Batch-invariant issue with google/universal-sentence-encoder-large

### ISSUE THREAD

**Issue by amitAI2402** [tensorflow/hub#74]
Hi Team,

Please find below sample code which i have written to generate sentence embedding vector using universal sentence encoder of large module version 2.

Problem here is that, i am receiving two different encoding vector for same string "The quick brown fox jumps over the lazy dog", if i use  below two scenarios.

a.  List contains only single string i.e. ["The quick brown fox jumps over the lazy dog"]
b. List contains more than one string i.e. ["The quick brown fox jumps over the lazy dog.","I am a sentence for which I would like to get its embedding"]

But as result, i am getting two different encoding vector for sentence "The quick brown fox jumps over the lazy dog".

import tensorflow as tf
import tensorflow_hub as hub

stringList=["The quick brown fox jumps over the lazy dog.","I am a sentence for which I would like to get its embedding"]

embed = hub.Module("https://tfhub.dev/google/universal-sentence-encoder-large/2")
embeddings = embed(stringList)

with tf.Session() as session:
        session.run(tf.global_variables_initializer())
        session.run(tf.tables_initializer())
        print session.run(embeddings)

stringList=["The quick brown fox jumps over the lazy dog."]

embeddings = embed(stringList)

with tf.Session() as session:
        session.run(tf.global_variables_initializer())
        session.run(tf.tables_initializer())
        print session.run(embeddings)

Also, i am working on to find similar sentences but due to different vector representations of same sentence when used in combination with other sentences is going to change which in turn effects similarity computation.  

Looking for your quick revert.

**Comment by andresusanopinto** [comment]
Hi Amit,

First of all thanks for providing reproduction instructions.

You are absolutely right that the computed embedding differs depending on the batch. The error also seems large to make it look like a numeric instability due to optimizations on the module when processing a batch. I will reach to the authors (and creators) of the module to comment.

On the meantime, notice that this issue was already present in https://tfhub.dev/google/universal-sentence-encoder-large/1 (so it is not a new issue with the version /2 of the module).

Cleaner sample to inspect this behavior:

```python
import tensorflow_hub as hub
import tensorflow as tf
import numpy as np
tf.logging.set_verbosity(0)

def make_embed_fn(module):
  with tf.Graph().as_default():
    sentences = tf.placeholder(tf.string)
    embed = hub.Module(module)
    embeddings = embed(sentences)
    session = tf.train.MonitoredSession()
  return lambda x: session.run(embeddings, {sentences: x})

f2 = make_embed_fn("https://tfhub.dev/google/universal-sentence-encoder-large/2")
f2_dup = make_embed_fn("https://tfhub.dev/google/universal-sentence-encoder-large/2")

x = [
  "The quick brown fox jumps over the lazy dog.",
  "I am a sentence for which I would like to get its embedding",
]

# Returns zeros showing the module is stable across instantiations.
print(np.linalg.norm(f2(x) - f2_dup(x)))

# ISSUE: returns 0.3 showing the embeddings per example depend on other elements in the batch.
print(np.linalg.norm(f2(x[0:1]) - f2(x)[0:1]))
```

**Comment by amitAI2402** [comment]
Hi,
Did you get chance to connect with creator of this module?

I am not sure but I think this issues could also be related to other encoding modules as well such as encoding for Wikipedia etc.

**Comment by amitAI2402** [comment]
Hi Team,

Any update on above issue

**Comment by andresusanopinto** [comment]
To be clear: other encoding modules (such as https://tfhub.dev/google/nnlm-en-dim50/1 or https://tfhub.dev/google/elmo/2) are not affected by this.

This should apply only to universal-sentence-encoder-large and we are still pending a concrete update to share.

**Comment by andresusanopinto** [comment]
Fixed in: https://tfhub.dev/google/universal-sentence-encoder-large/3.

The authors have fixed the issue and uploaded a new version.
This version was retraining and its embeddings don't match the old ones. All users of universal-sentence-encoder-large are encouraged to update! (the other versions of universal-sentence-encoder did not suffer from the issue).

**Comment by sekharvth** [comment]
It seems this issue is still prevalent. I'm using the Sentence Encoder version 3 as a part of my own network, and I was surprised to see different results when I ran my instances individually, and in batches.

I tested out the batch issue with this piece of code, and it outputs the number of elements in the 512-d embeddings, that are different among the single-instance-run and the batch-instance-run : 

`import tensorflow_hub as hub
embed = hub.Module(module_url)

import tensorflow as tf
count = 0
pos = 0
with tf.Session() as sess:
  sess.run(tf.tables_initializer())
  sess.run(tf.global_variables_initializer())
  emb1 = embed(["The quick brown fox jumped over the lazy dog"])
  emb2 = embed(["The quick brown fox jumped over the lazy dog",
"We should do this more often",
"This is a sentence that is to be tested",
"This is another sentence that is to be tested",
"Okay, because last time we talked it was like we were very confident that it would work right?",
"I need to better understand how this works"])
  for i,j in zip(sess.run(emb1)[0], sess.run(emb2)[0]):
    if i!=j:
      count+=1
      print (pos)
    pos+=1
print (count)`

The difference is only in the last few decimal places, but when it's used in a larger network, the difference becomes so significant as to produce wildly inconsistent outputs, while testing an instance individually, and in batches.

**Comment by akashjaswal** [comment]
Can confirm the above-mentioned behavior; Currently only satisfies the condition for the relative tolerance level of 1e-03 measured by [numpy isclose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.isclose.html) 

These subtle differences can fluctuate the downstream task performance significantly (~3% F1) when the vectors are fed as features into a model rather than just simply using a cosine similarity metric. 

```import numpy as np
import tensorflow as tf
import tensorflow_hub as hub

tran_encoder = hub.Module(
    "https://tfhub.dev/google/universal-sentence-encoder-large/3")
sentences = tf.placeholder(dtype=tf.string, shape=[None])
embedding_tran_func = tran_encoder(sentences)
sess_tran = tf.Session()
sess_tran.run([tf.global_variables_initializer(), tf.tables_initializer()])


def get_sentence_vectors(queries):
  return sess_tran.run(embedding_tran_func, feed_dict={sentences: queries})

embeddings_batch_one = get_sentence_vectors(
    ["The quick brown fox jumped over the lazy dog"])
embeddings_batch_two = get_sentence_vectors([
    "The quick brown fox jumped over the lazy dog",
    "We should do this more often",
    "This is a sentence that is to be tested",
    "This is another sentence that is to be tested",
    "Okay, because last time we talked it was like we were very confident that it would work right?",
    "I need to better understand how this works"
])


print(np.all(np.isclose(embeddings_batch_one[0], embeddings_batch_two[0], rtol=1e-03)))
print(np.all(np.isclose(embeddings_batch_one[0], embeddings_batch_two[0], rtol=1e-04)))
print(np.all(np.isclose(embeddings_batch_one[0], embeddings_batch_two[0], rtol=1e-05)))
print(np.all(np.isclose(embeddings_batch_one[0], embeddings_batch_two[0], rtol=1e-06)))
```

**Comment by FLamefiREz** [comment]
I have a problem, it should be a bug.
`import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text
sentence = "I am a sentence for which I would like to get its embedding."
embed = hub.load("https://hub.tensorflow.google.cn/google/universal-sentence-encoder-large/5")
embed(sentence)` 
It raised an error: 
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-1-78fad9923cf0> in <module>
     10 messages = [word, sentence, paragraph]
     11 embed = hub.load("https://hub.tensorflow.google.cn/google/universal-sentence-encoder-large/5")
---> 12 embed(sentence)

~/.conda/envs/zsm-gpu/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in _call_attribute(instance, *args, **kwargs)
    666 
    667 def _call_attribute(instance, *args, **kwargs):
--> 668   return instance.__call__(*args, **kwargs)
    669 
    670 

~/.conda/envs/zsm-gpu/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

~/.conda/envs/zsm-gpu/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    893       # If we did not create any variables the trace we have is good enough.
    894       return self._concrete_stateful_fn._call_flat(
--> 895           filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
    896 
    897     def fn_with_cond(inner_args, inner_kwds, inner_filtered_flat_args):

~/.conda/envs/zsm-gpu/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1917       # No tape is watching; skip to running the function.
   1918       return self._build_call_outputs(self._inference_function.call(
-> 1919           ctx, args, cancellation_manager=cancellation_manager))
   1920     forward_backward = self._select_forward_and_backward_functions(
   1921         args,

~/.conda/envs/zsm-gpu/lib/python3.7/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    558               inputs=args,
    559               attrs=attrs,
--> 560               ctx=ctx)
    561         else:
    562           outputs = execute.execute_with_cancellation(

~/.conda/envs/zsm-gpu/lib/python3.7/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError:  input must be a vector, got shape: []
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/text_preprocessor_1/tokenize/StringSplit/StringSplit}}]] [Op:__inference_restored_function_body_82308]

Function call stack:
restored_function_body`
`

**Comment by FLamefiREz** [comment]
import tensorflow as tf
import tensorflow_hub as hub

tran_encoder = hub.Module(
    "https://tfhub.dev/google/universal-sentence-encoder-large/3")
sentences = tf.placeholder(dtype=tf.string, shape=[None])
embedding_tran_func = tran_encoder(sentences)
sess_tran = tf.Session()
sess_tran.run([tf.global_variables_initializer(), tf.tables_initializer()])


def get_sentence_vectors(queries):
  return sess_tran.run(embedding_tran_func, feed_dict={sentences: queries})

embeddings_batch_one = get_sentence_vectors(
    ["The quick brown fox jumped over the lazy dog"])
embeddings_batch_two = get_sentence_vectors([
    "The quick brown fox jumped over the lazy dog",
    "We should do this more often",
    "This is a sentence that is to be tested",
    "This is another sentence that is to be tested",
    "Okay, because last time we talked it was like we were very confident that it would work right?",
    "I need to better understand how this works"
])


print(np.all(np.isclose(embeddings_batch_one[0], embeddings_batch_two[0], rtol=1e-03)))
print(np.all(np.isclose(embeddings_batch_one[0], embeddings_batch_two[0], rtol=1e-04)))
print(np.all(np.isclose(embeddings_batch_one[0], embeddings_batch_two[0], rtol=1e-05)))
print(np.all(np.isclose(embeddings_batch_one[0], embeddings_batch_two[0], rtol=1e-06)))

**Comment by FLamefiREz** [comment]
I have a problem with this module, it should be a bug.
```import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text
word = "Elephant"
sentence = "I am a sentence for which I would like to get its embedding."
paragraph = (
    "Universal Sentence Encoder embeddings also support short paragraphs. "
    "There is no hard limit on how long the paragraph is. Roughly, the longer "
    "the more 'diluted' the embedding will be.")
messages = [word, sentence, paragraph]
embed = hub.load("https://hub.tensorflow.google.cn/google/universal-sentence-encoder-large/5")
embed(sentence)
```

It raised an error:
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-1-78fad9923cf0> in <module>
     10 messages = [word, sentence, paragraph]
     11 embed = hub.load("https://hub.tensorflow.google.cn/google/universal-sentence-encoder-large/5")
---> 12 embed(sentence)

~/.conda/envs/zsm-gpu/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in _call_attribute(instance, *args, **kwargs)
    666 
    667 def _call_attribute(instance, *args, **kwargs):
--> 668   return instance.__call__(*args, **kwargs)
    669 
    670 

~/.conda/envs/zsm-gpu/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

~/.conda/envs/zsm-gpu/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    893       # If we did not create any variables the trace we have is good enough.
    894       return self._concrete_stateful_fn._call_flat(
--> 895           filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
    896 
    897     def fn_with_cond(inner_args, inner_kwds, inner_filtered_flat_args):

~/.conda/envs/zsm-gpu/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1917       # No tape is watching; skip to running the function.
   1918       return self._build_call_outputs(self._inference_function.call(
-> 1919           ctx, args, cancellation_manager=cancellation_manager))
   1920     forward_backward = self._select_forward_and_backward_functions(
   1921         args,

~/.conda/envs/zsm-gpu/lib/python3.7/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    558               inputs=args,
    559               attrs=attrs,
--> 560               ctx=ctx)
    561         else:
    562           outputs = execute.execute_with_cancellation(

~/.conda/envs/zsm-gpu/lib/python3.7/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError:  input must be a vector, got shape: []
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/text_preprocessor_1/tokenize/StringSplit/StringSplit}}]] [Op:__inference_restored_function_body_82308]

Function call stack:
restored_function_body
```

**Comment by sekharvth** [comment]
It's not a problem with the module, it's a bug in your code. `embed()` expects a list of inputs, not a string. So even if it's one string, that must be enclosed in a list. 
Change `sentence = "I am a sentence for which I would like to get its embedding."` to `sentence = ["I am a sentence for which I would like to get its embedding."]` , and it should work

**Comment by FLamefiREz** [comment]
> 这不是模块的问题，这是代码中的错误。`embed()`需要输入列表，而不是字符串。因此，即使是一个字符串，也必须将其括在列表中。
> 更改`sentence = "I am a sentence for which I would like to get its embedding."`为`sentence = ["I am a sentence for which I would like to get its embedding."]`，它应该可以正常工作

It works. Thanks!
